### ISSUE TITLE
Sort responses alphabetically

### ISSUE THREAD

**Issue by barriosnahuel** [notwaldorf/github-canned-responses#11]
When sorted we can find them easily. It would be great to get them sorted.

Thanks for the extension, it's very useful!

**Comment by notwaldorf** [comment]
Oh, that's a great idea. I'll take a look

**Comment by notwaldorf** [comment]
Thanks for the suggestion. Unfortunately, this element is no longer maintained since GitHub shipped this as a built-in feature
