### ISSUE TITLE
Feature Request: Automatic Popup for Canned response.

### ISSUE THREAD

**Issue by zkanda** [notwaldorf/github-canned-responses#19]
Hello,

Thank you very much for creating this project, really a great idea.

Just one feature request: Listen to the form and if there's a match then pop-up a choice of response.

Example:
When I type "PR" in the form, there would be a selection and I can select a canned response, it would be much faster if I don't need to reach for my mouse and selecting a choice.

**Comment by notwaldorf** [comment]
Thanks for the suggestion. Unfortunately, this element is no longer maintained since GitHub shipped this as a built-in feature
