### ISSUE TITLE
seems to be broken as of now

### ISSUE THREAD

**Issue by despairblue** [notwaldorf/github-canned-responses#22]
The menu does not show up. Probably because of github changes concerning the added reactions.

**Comment by notwaldorf** [comment]
@despairblue Is this on Firefox? I see it on Chrome fine (and shouldn't be affected by reactions, since they're in a different CSS container)

**Comment by despairblue** [comment]
@notwaldorf right, silly me, [refined github](https://github.com/sindresorhus/refined-github/) hides the whole menu.

Sry for the inconvenience :smile:

**Comment by notwaldorf** [comment]
No worries!
