### ISSUE TITLE
Deprecation

### ISSUE THREAD

**Issue by gytdau** [notwaldorf/github-canned-responses#23]
Should this repository be deprecated, seeing as GitHub now offers their own canned responses?

https://github.com/blog/2135-saved-replies

**Comment by leesei** [comment]
@notwaldorf We appreciate you efforts but please at least add a note of the official feature to the README.

**Comment by notwaldorf** [comment]
I've added a note to the readme, but it's not like I'm forcing you to use this extension. There's no real point in deprecating the repo, since the code still works and whether or not you want to use this or GitHub's actual feature is entirely your choice.
