### ISSUE TITLE
Broken in Chrome 55.0.2883.59 beta (64-bit)

### ISSUE THREAD

**Issue by staff0rd** [notwaldorf/github-canned-responses#26]
Heya, it doesn't seem that any button is added to the edit panel to access the canned responses, meaning it doesn't look like this works anymore.

Also, I was unaware that github had implemented "Saved Replies" - it might be nice for the chrome store page for the extension to note that github implemented the functionality natively.

**Comment by notwaldorf** [comment]
Closing; this element is no longer maintained since GitHub shipped this as a built-in feature
