### ISSUE TITLE
Enhancement: Utilize chrome.storage API

### ISSUE THREAD

**Issue by pRizz** [notwaldorf/github-canned-responses#27]
This API has a few benefits over the `localStorage` object:
- it lets you access storage without the need of a handler in the background script
- store arbitrary objects - no need to JSON stringify and parse

There are also a few different flavors of the api: `local`, `sync`, and `managed`. The `sync` version syncs storage across your Chrome enabled devices!

More info: https://developer.chrome.com/extensions/storage

Nice job on this extension btw. I just published an extension very similar to this, but only found yours just now, heh. https://chrome.google.com/webstore/detail/github-comment-injector/ajofdhfamkhocankdlajjmadjmcnmneo

**Comment by notwaldorf** [comment]
Thanks for the suggestion. Unfortunately, this element is no longer maintained, since GitHub has published this as a built-in feature
