### ISSUE TITLE
Pick current item with [ENTER] and [TAB]

### ISSUE THREAD

**Issue by triblondon** [notwaldorf/github-canned-responses#5]
This is a wonderful extension. It frustrates me that I can't press enter to select an item though. If that's a feature you'd agree to add, I'd be happy to contribute a PR.

**Comment by josh** [comment]
Should be fixable when @notwaldorf switches over to using the @github's "select menu" related events rather than binding to `click` itself.

**Comment by notwaldorf** [comment]
Which should be fixed when @josh ships a fix in GitHub (we wait patiently) 😄

**Comment by triblondon** [comment]
OK, right then [backs away slowly]

**Comment by notwaldorf** [comment]
Thanks for the suggestion. Unfortunately, this element is no longer maintained since GitHub shipped this as a built-in feature
